### ISSUE TITLE
GD 2.50 のインストールができない

### ISSUE THREAD

**Issue by nanto** [wakaba/perl-setupenv#3]
某プロジェクトでは GD 2.50 を使っているが、GD 2.50 は `Makefile.PL` を用いるため、 bd84ed30f6a5fa273e753013e89d899e3f975474 が入って以降は pmbp でのインストールに失敗する。

某プロジェクトの方で依存する GD のバージョンを上げられればよいのだが、それもそれでなかなか難しそうな模様 ><

**Comment by wakaba** [comment]
Build.PL がなければ Makefile.PL にフォールバックするようにしてみました。これでいかがでしょうか。

**Comment by nanto** [comment]
インストールできたっぽいです。迅速な対応ありがとうございました。
